apiVersion: v1
kind: Pod

metadata:
  name: go-pod

spec:
  containers:
    - name: golang-container
      image: go-server
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
