apiVersion: apps/v1
kind: Deployment

metadata:
  name: golang-deployment

# Deployment 세부 정보
spec:
  replicas: 3
  selector:
      matchLabels:
        app: backend-app # label과 똑같아야 함
  
  # 배포할 Pod 정의
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: go-container
          image: go-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
