apiVersion: apps/v1
kind: Deployment

metadata:
  name: golang-deployment

# Deployment 세부 정보
spec:
  replicas: 3
  selector:
      matchLabels:
        app: backend-app # label과 똑같아야 함
  
  # 배포할 Pod 정의
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: go-container
          image: go-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: EXAMPLE_ENV
              valueFrom:
                configMapKeyRef:
                  name: go-config
                  key: EXAMPLE_ENV
            - name: EXAMPLE_ENV2
              valueFrom:
                configMapKeyRef:
                  name: go-config
                  key: EXAMPLE_ENV2
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: go-secret-config
                  key: SECRET_KEY

