# eks에서 이걸 생성해서 적용하면 자동으로 ELB가 생성됨

apiVersion: v1
kind: Service

metadata:
  name: go-loadbalancer

spec:
  type: LoadBalancer
  selector: 
    app: backend-app # 이 label의 Pod에 제공하겠다
  ports:
    - protocol: TCP # 서비스에 접속하기 위한 프로토콜
      port: 8080 # 외부에서 사용자들이 접근하게 될 포트번호, 쿠버네티스 내부에서 Service에 접속하기 위한 포트번호는 자동으로 매핑됨
      targetPort: 8080 # 매핑하기 위한 파드의 내부 포트번호
      # nodePort: 30000 # 이게 자동으로 생성됨
      # nodePort -> port -> targetPort
