apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod

spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80 # 그냥 가독성에 대한 역할

# kubectl 띄우기
# kubectl apply -f nginx-pod.yaml
# 확인
# kubectl get pods
# 상세 확인
# kubectl describe pod nginx-pod
# 삭제
# kubectl delete pod nginx-pod
# 컨테이너 내부 접속
# kubectl exec -it nginx-pod -- bash
# 포트 포워딩(앞에 로컬, 80이 컨테이너 내부 포트)
# kubectl port-forward pod/nginx-pod 8080:80
